### PR TITLE
Add FileData and FileText

### PR DESCRIPTION
**Pull request by furudbat**
Add Wrapper for Files management functions (`LoadFileData`, `LoadFileText`, ...)

### CODE REVIEW

**Comment by RobLoach** [comment]
Great idea! 😉

**Comment by RobLoach** [comment]
With these additions, we'll be able to overload the other file methods too. Mind if we get a couple tests in place for them? Just something simple.

**Comment by abeimler** [comment]
Should be working I moved them from my other Project :^) ... I also added some tests.

I would recommend using a test framework like [Catch2](https://github.com/catchorg/Catch2) or [google-test](https://google.github.io/googletest/), like I did in [my fork](https://github.com/furudbat/raylib-cpp20/blob/main/tests/unit/raylib_cpp_test.cpp).

**Comment by furudbat** [comment]
Should be working I moved them from my other Project :^) ... I also added some tests.

I would recommend using a test framework like [Catch2](https://github.com/catchorg/Catch2) or [google-test](https://google.github.io/googletest/), like I did in [my fork](https://github.com/furudbat/raylib-cpp20/blob/main/tests/unit/raylib_cpp_test.cpp).

**Comment by RobLoach** [comment]
Was considering catch2 a while ago, but wanted to keep the syntax similar to raylib formatting. And just needed some simple assertions anyway 😉

**Pull request merged**
