### PR TITLE
Added a VSCode project folder along with a README for instructions.

### PR DESCRIPTION
**Pull request by KnockerPulsar**

### CODE REVIEW

**Comment by RobLoach** [comment]
Nice work! Do we need the `.vscode` directory here??? Or is that all personal config stuff?

**Comment by KnockerPulsar** [comment]
> Nice work! Do we need the `.vscode` directory here??? Or is that all personal config stuff?

Yep, it's required to tell VSCode how to go about compiling the code.

**Comment by RobLoach** [comment]
The .vscode directory may have been gitignored... We can make a `.gitignore` with !.vscode to un-ignore it in this directory.

**Comment by KnockerPulsar** [comment]
Ok, I think this should do it. Sorry about that mistake.

**Pull request merged**
