### PR TITLE
Reduction of the number of constructors for `raylib::Rectangle`

### PR DESCRIPTION
**Pull request by Bigfoot71**
I reduced the number of constructors for `raylib::Rectangle` using default parameters.

### CODE REVIEW

**Comment by RobLoach** [comment]
Thanks. I forget why I opted to manually implement these. I think there was an issue with one version of C++ that had conflict between the default parameters and initializer lists.

**Comment by Bigfoot71** [comment]
I personally have no problem compiling it with GCC 11.4.0, whether it's with `-std=c++11` or `-std=c++17`. I could perform more thorough tests when I have the time, if you'd like.

**Comment by kyomawolf** [comment]
Whats up with this PR? Do you know why the build fails?

**Comment by RobLoach** [comment]
If we do take this approach, I'd like to do a few things...
- Add more tests to make sure the constructors still work properly
- Apply the same pattern across the rest of the data types

I do remember running into an issue with the initializer list understanding the default parameters, but I'm not sure where/when it happened.

**Pull request closed without merging**
